### PR TITLE
Fix #23: crashes when no argument given

### LINKED ISSUE #23: 'Unknown encoding: null' due to passing wrong argument to Buffer#toString()
I just searched for a tmux replacement using NPM today and found this. Seems perfect. The only issue is that it crashed on first try! And it did this on all Node versions and on both macOS (ARM) and Linux (x86).

If you start up stmux without any arguments and press any key it will crash:
```
$ npx stmux

Unknown encoding: null
```

Just wanted to register the issue before filing a fix. I have verified this issue with Node 12, 14 and 16, so I am not sure why no one has reported, as the code is untouched since 2017 and it can't ever have worked. The above error is for Node 12 and 14, Node 16 is more explicit: 
```
node:buffer:809
    throw new ERR_UNKNOWN_ENCODING(encoding);
    ^

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: null
    at new NodeError (node:internal/errors:371:5)
    at Buffer.toString (node:buffer:809:11)
    at STMUX.parseOptions (/Users/carlerik/.npm/_npx/feb1cc2f2f2b52b3/node_modules/stmux/bin/stmux-1-options.js:153:28)
    at STMUX.main (/Users/carlerik/.npm/_npx/feb1cc2f2f2b52b3/node_modules/stmux/bin/stmux.js:54:10)
    at Object.<anonymous> (/Users/carlerik/.npm/_npx/feb1cc2f2f2b52b3/node_modules/stmux/bin/stmux.js:77:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'ERR_UNKNOWN_ENCODING'
}
```

### PR DESCRIPTION
**Pull request by fatso83**
# Intent
The passed in 'null' is an invalid value for encoding when calling [Buffer#toString](https://nodejs.org/api/buffer.html#buftostringencoding-start-end). This fixes #23.

Verified for Node 12-16

# Other changes

It turned out that the Makefile was written in a way that caused the build to re-run always, no matter if files had changed or not, so I fixed the Makefile to only recompute when needed. I also created a test runner in bash to be able to test drive the fix automatically and have a regression test, since I could not see any tests. Only after making this I found that you actually have a little test driver in `npm test`. I moved that as a test into the test runner to keep all the tests in a single location and made NPM delegate to Make for consistency.

# Verification
The following script is executed _after_ checking out this branch and then doing `git checkout 1.8.2 src/stmux-1-options.js` in able to show the bug before and after the fix (but still using the test runner):
Skjermbilde 2021-11-05 kl  23 06 24

### CODE REVIEW

**Comment by rse** [comment]
I think passing "undefined" instead of "null" is also not really the right thing. For reading from stdin we usually want to enforce UTF-8, I think. I've changed it now this way.

**Comment by rse** [comment]
The Makefile is just for me (an old Unix hacker), not for the NPM world itself. Hence, I've intentionally just call NPM from Make, but not vice versa (as the usual NPM user has no Unix environment at hand). Hence, it would be better to not take over these changes. The encoding problem I've fixed instead.

**Comment by fatso83** [comment]
> as the usual NPM user has no Unix environment at hand

Actually, if this was true, no-one would be able to use this package! This package transitively relies on node-gyp, which means installations fail if they miss make. I realised this when adding stmux to our project and our ci server build failed 😅

**Comment by rse** [comment]
Really? I have co-workers which uses it (at least in the past) on a Windows (non-WSL) console. If node-gyp would always require make, nobody could use any node-pty based NPM package under Windows. One needs the "windows-build-tools" there. Perhaps this somewhere also install a "make" clone. At least the every NPM user under Windows has no "make" in their $PATH, I'm sure ;-)

**Comment by fatso83** [comment]
That's absolutely true. Windows users utilize the MSBUILD build toolchain, which can be installed with the default Node install. Windows users are a bit of an exception; they are rarely the ones that ends up building something like this from scratch, and the ones that do usually do so using WSL2 anyhow. The rest, the macOS and *nix crowd, at least needs make for node-gyp 🙂

**Pull request closed without merging**
